### ISSUE TITLE
Error when running creator.py

### ISSUE THREAD

**Issue by mvaaltola** [GispoCoding/qgis_plugin_tools#45]
Running `$ python creator.py -o GispoCoding -r test -u https://github.com` results in:

```
.qgis-plugin-ci
.pre-commit-config.yaml
.editorconfig
setup.cfg
requirements-dev.txt
README.md
LICENSE
.gitignore
docs/development.md
docs/push_translations.yml
CHANGELOG.md
.github/workflows/tests.yml
Traceback (most recent call last):
  File "/home/mikael/git/kimu/KiMu/creator.py", line 4, in <module>
    create_plugin()
  File "/home/mikael/git/kimu/KiMu/qgis_plugin_tools/infrastructure/plugin_creator.py", line 185, in create_plugin
    creator.create()
  File "/home/mikael/git/kimu/KiMu/qgis_plugin_tools/infrastructure/plugin_creator.py", line 79, in create
    self.copy_and_edit_file(ROOT_DIR, f)
  File "/home/mikael/git/kimu/KiMu/qgis_plugin_tools/infrastructure/plugin_creator.py", line 134, in copy_and_edit_file
    shutil.copy2(f, dst_file)
  File "/usr/lib/python3.9/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '.github/workflows/tests.yml'
```

Possibly related to #43

**Comment by Joonalai** [comment]
We will get rid of the `creator.py` completely soon, so I think this will not be fixed.

**Comment by mvaaltola** [comment]
#46
